<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SonarCommon.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blurhash.Core" Version="4.0.0" />
    <PackageReference Include="DryIoc.dll" Version="5.4.3" />
    <PackageReference Include="DryIoc.MefAttributedModel.dll" Version="7.0.2" />
    <PackageReference Include="FileSystemLinks" Version="1.0.3" />
    <PackageReference Include="Humanizer" Version="3.0.10" />
    <PackageReference Include="Magick.NET-Q8-x64" Version="14.16.0" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.11" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sonar\Sonar.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BCnEncoder">
      <HintPath>..\SonarResources.libs\BCnEncoder.dll</HintPath>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>..\SonarResources.libs\Lumina.dll</HintPath>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>..\SonarResources.libs\Lumina.Excel.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>